import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const rodin = localFont({
  src: "../../public/fonts/RodinBokutoh.otf",
  variable: "--font-rodin",
});

const seurat = localFont({
  src: "../../public/fonts/Seurat.otf",
  variable: "--font-seurat",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${rodin.variable} ${seurat.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
